language: python

python:
    - "2.6"
    - "2.7"

env:
    - DJANGO=1.4.6
    - DJANGO=1.5.2

install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors

script:
    - coverage run test_suite.py

after_success:
    - coveralls
